services:
    - docker

notifications:
    email:
        on_success: never

before_deploy:
    - name="cntr-$TRAVIS_TAG-$TARGET"
    - depsname="cntr-src-$TRAVIS_TAG"
    - install -D target/$TARGET/release/cntr $name/cntr
    - install -D target/$TARGET/release/cntr cntr-bin-$TRAVIS_TAG-$TARGET
    - mkdir $depsname
    - git archive HEAD | tar -x -C $depsname
    - cargo vendor
    - mv vendor $depsname/
    - tar czvf $depsname.tar.gz $depsname

deploy:
    skip_cleanup: true
    provider: releases
    api_key:
        secure: m1oHTX3v5x5VRmUCwG9nPI8pKrg2BBg6VCv6XgXhadSILtV562uQvHSd0/ruqsEnxp8giYX0i5T7BA0pH7WrQVDIOIk2I7gV1DwhKOQEb3q8Z8/cyk/b3urKLUqWHOLPW2ptfUEO4w4hv2nzZ8X+PDcAizu1pIjnzm2h4v1xl+vT8qJyd+m88L+g8VuLuek3HXgQqUHjHwlHJqhzZ5aRmp3vMszQa8TURM4Lwtd2jrVmWxcXVnyUX4vjuVlZD5c1S/3nujnAqxLOrj3EZpH7Ur3G1EwyDoFnllwmxLrvmHs3dXMjvjThtm4ZNM3bMjqJ/RJNQmY4TJQbiDcuf0Mt+bM9Qd8vn0jtFFSnOVfiVi4Cd4ndax0VswVYuOcHMDfVuiMAKUdxk/GkCZDba20wrnfHJizYZyyf3PSzxKQT6urulwS0dog0i0DQJ2v4Bc3WXFbvqhLMGYEH0IEaG/KAa9TKp51fTIZvIddqsp2dpfZxOKnlP3pgPQuiy/1120oqgDNPLOwd/Zy++ta+wMCVLpsc9oEaSnn6kvLV6HEi1hFMr0bpDltQz1GoaPe5HtfJMFKT5fWsMpF/OttXHD5XDcBprEy04DfiA1pSzeM1IMvkatIy67QwpNAGlVhQyANgJUjbH/WsuGxO/up9P6P+VGYJX71Aso6/mM/SvfU9qno=
    file_glob: true
    file:
        - cntr-$TRAVIS_TAG-$TARGET.tar.gz
        - cntr-src-$TRAVIS_TAG.tar.gz
        - cntr-bin-$TRAVIS_TAG-$TARGET
    on:
        repo: Mic92/cntr
        tags: true